FROM python:3.10-slim-bookworm
RUN apt-get update

# Networking
RUN apt-get install -y iproute2 ethtool iputils-ping

# Create app directory
WORKDIR /app

# Python Libraries
COPY requirements.txt ./
RUN pip install -r requirements.txt

# Utility
RUN apt-get install -y wget

# Copy Fl Source
COPY . .