FROM python:3.10-slim-bookworm
RUN apt-get update

# Networking
RUN apt-get install -y iproute2 ethtool iputils-ping

# Create app directory
WORKDIR /app

# Python Libraries
COPY requirements.txt ./
RUN pip install -r requirements.txt
RUN pip install torch==2.0.1 torchvision==0.15.2 --index-url https://download.pytorch.org/whl/cpu

# Utility
# RUN apt-get install -y wget

# Copy Fl Source
COPY . .